language: python
python:
  - 3.5

before_install:
  - deactivate
  - sudo apt-add-repository --yes ppa:mapnik/nightly-2.3
  - sudo apt-get update -qq
  - sudo apt-get install -y libmapnik mapnik-utils python-mapnik
  - virtualenv --system-site-packages venv
  - source venv/bin/activate
  - pip install -r requirements.txt
install:
  - python setup.py develop
before_script:
  - pip install nose
  - pip install coverage
script:
  - nosetests --with-coverage --cover-package=landez
after_success:
  - pip install coveralls
  - coveralls
